# Generated by Django 4.1.7 on 2023-04-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_bubbletea_cliente_proveedor_delete_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bubbletea',
            name='tipo_de_te',
        ),
    ]
