# Generated by Django 4.1.7 on 2023-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_remove_bubbletea_tipo_de_te'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Suscriptor',
        ),
        migrations.RenameModel(
            old_name='BubbleTea',
            new_name='Viaje',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='toppins',
            new_name='personas',
        ),
    ]
