# Generated by Django 4.1.7 on 2023-04-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_itinerario_rename_cliente_suscriptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=50)),
                ('estrellas', models.IntegerField()),
            ],
        ),
    ]
