# Generated by Django 4.1.7 on 2023-04-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='comentario',
            new_name='reseña',
        ),
    ]
