# Generated by Django 4.1.7 on 2023-04-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_rename_comentario_comentarios_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='reseña',
            field=models.CharField(max_length=140),
        ),
    ]
