# Generated by Django 4.1.7 on 2023-04-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_comentarios_reseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerario',
            old_name='empresa',
            new_name='region',
        ),
    ]
