# Generated by Django 4.1.7 on 2023-04-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_rename_empresa_itinerario_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itinerario',
            new_name='Itinerarios',
        ),
    ]
